# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev wget
  
r:
  - oldrel
  - release
  - devel

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
  - wget https://mybinder.org/v2/gh/seabbs/getTBinR/master?urlpath=rstudio
